version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ciclozero
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: ciclozero_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge
